version: "3"
services:
  todolist-db:
    image: mariadb:11.1.2
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: todolist
      TZ: "Europe/Zurich"
    volumes:
      - datadir:/var/lib/mysql

  todolist-frontend:
    build: ./frontend
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  todolist-backend:
    image: todolist-be
    depends_on:
      - todolist-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://todolist-db:3306/todolist
    ports:
      - "8080:8080"

volumes:
  datadir:
